INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Esteban', 'Gallar', 'esteban_2189@hotmail.com','2022-09-22');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Lionel', 'Messi', 'lionel.messi@gmail.com', '2022-09-22');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Angel', 'Di Maria', 'angel.dimaria@gmail.com', '2018-11-15');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rodrigo', 'De Paul', 'rodrigo.depaul@gmail.com', '2017-04-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Juan Roman', 'Riqulme', 'roman.riquelme@gmail.com', '2000-07-31');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Sergio', 'Agüero', 'sergio.aguero@gmail.com', '2015-12-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Agustin', 'Rossi', 'agustin.rossi@gmail.com', '2010-05-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Lionel', 'Scaloni', 'lionel.scaloni@gmail.com', '2005-03-30');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Angel', 'Correa', 'angel.correa@gmail.com', '2019-10-12');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Leandro', 'Paredes', 'leandro.paredes@gmail.com', '2006-10-02');
